### ISSUE TITLE
BUG: Referencing another sheet cell that is named a number (ie 2024) just results in name of sheet

### ISSUE THREAD

**Issue by jwjenkin** [ironcalc/IronCalc#485]
Example:
* Enter `='2024'!A1`
  * Result is `2024`
  * Clicking the cell shows `=2024`

Expected:
* Enter `='2024'!A1`
  * Result is value of Sheet `2024`, Cell `A1`

**Comment by nhatcher** [comment]
Fixed and fixed deployed. Please check

**Comment by jwjenkin** [comment]
Looks like it fixed the ref, but the formula still shows up as `=2024` (after an import) so that if I accidentally hit enter it resets.

Then re-entering as `='2024'!A1` changes to `=2024!A1`, which goes back to `2024` as the value :)

But! Progress!
